title: Scholar
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
  description: 'Scholar is an academic-focused theme, for publishing papers, articles, books, documentation, your resumé or other content with Grav.'
